test

diff --git a/.github/actions/load-env-file/action.yml b/.github/actions/load-env-file/action.yml
--- a/.github/actions/load-env-file/action.yml
+++ b/.github/actions/load-env-file/action.yml
@@ -9,6 +9,9 @@ inputs:
     default: 'development'
     required: false
 outputs:
+  environment:
+    description: "The target environment for the deployment"
+    value: ${{ steps.variables.outputs.environment }}
   github_infra_repo_username:
     description: "The username where the infrastructure repository is registered to"
     value: ${{ steps.variables.outputs.github_infra_repo_username }}
@@ -24,6 +27,16 @@ outputs:
   dora_metrics:
     description: "If you want to generate DORA metrics. values: TRUE||FALSE"
     value: ${{ steps.variables.outputs.dora_metrics }}
+  image_name:
+    description: "Name of the image you want to build"
+    value: ${{ steps.variables.outputs.image_name }}
+  original_image_repository:
+    description: "Name of the repository where the image is going to be promoted from"
+    value: ${{ steps.variables.outputs.original_image_repository }}
+  target_image_repository:
+    description: "Name of the repository where the image is going to be promoted to"
+    value: ${{ steps.variables.outputs.target_image_repository }}
+
 runs:
   using: "composite"
   steps:
@@ -38,8 +51,25 @@ runs:
       id: variables
       shell: bash
       run: |
-        echo "github_infra_repo_username=${{ env.GITHUB_INFRA_REPO_USERNAME }}" >> "$GITHUB_OUTPUT"
-        echo "github_infra_repo_name=${{ env.GITHUB_INFRA_REPO_NAME }}" >> "$GITHUB_OUTPUT"
-        echo "github_application_repo_commit_username=${{ env.GITHUB_APPLICATION_REPO_COMMIT_USERNAME }}" >> "$GITHUB_OUTPUT"
-        echo "github_application_repo_commit_user_email=${{ env.GITHUB_APPLICATION_REPO_COMMIT_USER_EMAIL }}" >> "$GITHUB_OUTPUT"
-        echo "dora_metrics=${{ env.DORA_METRICS }}" >> "$GITHUB_OUTPUT"
+        if [ "${{ inputs.mode }}" == "development" ]; then
+          # Development mode specific actions
+          echo "environment=${{ env.ENVIRONMENT }}" >> "$GITHUB_OUTPUT"
+          echo "github_infra_repo_username=${{ env.GITHUB_INFRA_REPO_USERNAME }}" >> "$GITHUB_OUTPUT"
+          echo "github_infra_repo_name=${{ env.GITHUB_INFRA_REPO_NAME }}" >> "$GITHUB_OUTPUT"
+          echo "github_application_repo_commit_username=${{ env.GITHUB_APPLICATION_REPO_COMMIT_USERNAME }}" >> "$GITHUB_OUTPUT"
+          echo "github_application_repo_commit_user_email=${{ env.GITHUB_APPLICATION_REPO_COMMIT_USER_EMAIL }}" >> "$GITHUB_OUTPUT"
+          echo "dora_metrics=${{ env.DORA_METRICS }}" >> "$GITHUB_OUTPUT"
+          echo "image_name=${{ env.IMAGE_NAME }}" >> "$GITHUB_OUTPUT"
+        elif [ "${{ inputs.mode }}" == "acceptance" ]; then
+          # Acceptance mode specific actions
+          echo "environment=${{ env.ENVIRONMENT_PROD }}" >> "$GITHUB_OUTPUT"
+          echo "github_infra_repo_username=${{ env.GITHUB_INFRA_REPO_USERNAME_PROD }}" >> "$GITHUB_OUTPUT"
+          echo "github_infra_repo_name=${{ env.GITHUB_INFRA_REPO_NAME_PROD }}" >> "$GITHUB_OUTPUT"
+          echo "github_application_repo_commit_username=${{ env.GITHUB_APPLICATION_REPO_COMMIT_USERNAME_PROD }}" >> "$GITHUB_OUTPUT"
+          echo "github_application_repo_commit_user_email=${{ env.GITHUB_APPLICATION_REPO_COMMIT_USER_EMAIL_PROD }}" >> "$GITHUB_OUTPUT"
+          echo "original_image_repository=${{ env.ORIGINAL_IMAGE_REPOSITORY }}" >> "$GITHUB_OUTPUT"
+          echo "target_image_repository=${{ env.TARGET_IMAGE_REPOSITORY }}" >> "$GITHUB_OUTPUT"
+        else
+          echo "Invalid mode provided."
+          exit 1
+        fi
